---
- name: PHP - Add Repository
  apt_repository: repo="ppa:ondrej/php5" update_cache=yes
- name: PHP - Install
  apt: pkg=$item state=installed
  with_items:
    - php5
    - php5-cli
    - php5-xdebug
    - php5-curl
    - php5-dev
    - php-pear
